name: Android Preview
on:
  push:
    branches: [ "main" ]
jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci
      - name: EAS CLI
        run: npm i -D eas-cli
      - name: Build Android (preview)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas build -p android --profile preview --non-interactive
