name: EAS Update (preview)

on:
  push:
    branches: [ "main" ]

jobs:
  ota-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS Update to preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas whoami
          eas update --branch preview --message "CI: ${{ github.sha }}"
